default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USERNAME_POSTGRESQL"] %>
  password: <%= ENV["PASSWORD_POSTGRESQL"] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: usermessage

test:
  <<: *default
  database: user_message_test

production:
  <<: *default
  database: user_message_production
